baseURL = "http://gyanfull.in/"
languageCode = "en-us"
title = "Gyanfull"
theme = "hugo-ink"
copyright = "©Ajay Nadathur, 2020. Unauthorized use of this material without permission is strictly prohibited."
googleAnalytics = "UA-156965118-1"

[params]
    subtitle = "My reflections on tech, book reviews, life, travel and more"
    avatar = "/images/seal.png"
	featherIconsCDN = true
	mode = "auto"

[markup.goldmark.renderer]
unsafe= true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ajaykumarns"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ajaykumarns"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ajayk3/"
