name: Build site on master

on:
  push:
    branches: 
      - site

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Checkout the site brranch
      run: git checkout site 
    - name: Build and publish master branch
      run: |
        sh publish.sh
        cd public
        git push origin master
